(async function(){
  const config=window.__PLANA_SHELL_CONFIG__||{};
  const root=document.getElementById('view-root'),status=document.getElementById('page-status'),title=document.getElementById('page-title'),caption=document.getElementById('page-caption'),subnav=document.getElementById('subnav');
  const memoryStore={};let locale='zh-CN',activeSection='overview',activeSubview='';
  function storageGet(key){try{return localStorage.getItem(key)||''}catch(e){return memoryStore[key]||''}}
  function storageSet(key,value){try{localStorage.setItem(key,String(value))}catch(e){memoryStore[key]=String(value)}}
  function t(key){return (window.PlanaI18n[locale]||window.PlanaI18n['zh-CN'])[key]||key}
  function esc(value){return String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]))}
  function label(value){const map={enabled:'已启用',disabled:'已禁用',degraded:'降级',completed:'已完成',succeeded:'已完成',success:'成功',waiting_confirm:'待确认',pending:'待处理',queued:'排队中',active:'可用',available:'可用',waiting:'等待中',unverified:'未验证',safe:'安全',verified:'已验证',exported:'已发布',restricted:'受限',protected:'受保护',read_only_external:'外部只读',issue:'异常',error:'异常',failed:'失败',running:'处理中',submitted:'已提交',cancelling:'正在取消',cancel_failed:'取消未成功',cancelled:'已取消',rejected:'已拒绝',blocked:'已阻止',expired:'已过期',interactive:'交互任务',long:'长任务',background:'后台任务',low:'低',medium:'中',high:'高'};return locale==='zh-CN'?(map[String(value)]||String(value||'-')):String(value||'-').replaceAll('_',' ')}
  function tag(value,tone=''){return `<span class="tag ${tone}">${esc(label(value))}</span>`}
  function tech(value){return `<details class="tech-details"><summary>${t('common.technical')}</summary><pre>${esc(JSON.stringify(value,null,2))}</pre></details>`}
  function empty(message,action=''){return `<div class="empty-state"><p>${esc(message)}</p>${action}</div>`}
  function table(headers,rows){return `<div class="table-scroll"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">${t('common.none')}</td></tr>`}</tbody></table></div>`}
  function sectionHeading(name,description,meta=''){return `<div class="section-heading"><div><h2>${esc(name)}</h2>${description?`<p>${esc(description)}</p>`:''}</div>${meta}</div>`}
  const nativeFetch=window.fetch.bind(window);
  if(config.bridgeMode){
    const bridge=window.__planaPluginPageBridge||window.AstrBotPluginPage;const base='/__plana_bridge_api__';
    window.fetch=async(input,opts={})=>{const raw=typeof input==='string'?input:(input&&input.url)||'',url=new URL(raw,location.href);if(!url.pathname.startsWith(base+'/')||!bridge)return nativeFetch(input,opts);try{const endpoint=url.pathname.slice(base.length+1),params=Object.fromEntries(url.searchParams.entries()),method=String(opts.method||'GET').toUpperCase();let payload;if(method==='GET')payload=await bridge.apiGet(endpoint,params);else payload=await bridge.apiPost(endpoint,opts.body?JSON.parse(opts.body):{});const normalized=payload&&typeof payload==='object'&&('ok'in payload||'data'in payload||'result'in payload)?payload:{ok:true,data:payload};return new Response(JSON.stringify(normalized),{status:200,headers:{'Content-Type':'application/json'}})}catch(error){return new Response(JSON.stringify({ok:false,error:String(error&&error.message||error)}),{status:502,headers:{'Content-Type':'application/json'}})}};
  }
  async function api(path,options={}){const response=await fetch(config.apiBase+path,options),data=await response.json().catch(()=>({ok:false,error:'invalid_response'}));if(!response.ok||data.ok===false)throw Object.assign(new Error(data.error||`request_${response.status}`),{detail:data});return data}
  const ctx={api,t,esc,label,tag,tech,empty,table,sectionHeading,storageGet,storageSet,preserveViewState,get locale(){return locale},get activeSubview(){return activeSubview},setSubview,navigate};
  function applyI18n(){document.documentElement.lang=locale;document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-aria-label]').forEach(el=>el.setAttribute('aria-label',t(el.dataset.i18nAriaLabel)))}
  function setSubview(name){activeSubview=name;return renderSection(false)}
  async function preserveViewState(container,render,requestedFocusKey=''){const scroll=Array.from(container.querySelectorAll('[data-preserve-scroll]')).map((node,index)=>({key:node.dataset.preserveScroll||String(index),top:node.scrollTop,left:node.scrollLeft})),active=document.activeElement,focusKey=requestedFocusKey||(container.contains(active)?active.getAttribute('data-preserve-focus'):'');const page={x:window.scrollX,y:window.scrollY};await render();scroll.forEach((item)=>{const node=container.querySelector(`[data-preserve-scroll="${CSS.escape(item.key)}"]`);if(node){node.scrollTop=item.top;node.scrollLeft=item.left}});if(focusKey){container.querySelector(`[data-preserve-focus="${CSS.escape(focusKey)}"]`)?.focus({preventScroll:true})}window.scrollTo(page.x,page.y)}
  async function navigate(section,subview=''){await switchSection(section);if(subview){activeSubview=subview;await renderSection(false)}}
  function renderSubnav(items){subnav.hidden=!items.length;subnav.innerHTML=items.map(item=>`<button type="button" class="${item.id===activeSubview?'active':''}" data-subview="${item.id}">${t(item.label)}</button>`).join('');subnav.querySelectorAll('button').forEach(button=>button.onclick=()=>setSubview(button.dataset.subview))}
  function showLoading(){root.setAttribute('aria-busy','true');root.innerHTML='<div class="view-stack"><div class="skeleton"></div><div class="skeleton"></div><div class="skeleton"></div></div>';status.textContent=t('common.loading')}
  function showError(error){root.removeAttribute('aria-busy');status.textContent='';root.innerHTML=`<div class="error-state"><h2>${locale==='zh-CN'?'页面暂时无法加载':'This page could not load'}</h2><p>${locale==='zh-CN'?'请检查相关服务后重试。':'Check the related service and retry.'}</p><button class="btn primary" id="retry-view" type="button">${t('common.retry')}</button>${tech({message:error&&error.message,detail:error&&error.detail})}</div>`;document.getElementById('retry-view').onclick=()=>renderSection(false)}
  async function renderSection(focus=true){const view=window.PlanaViews&&window.PlanaViews[activeSection];if(!view)return;const meta=view.meta||{};if(!activeSubview||!meta.subviews?.some(x=>x.id===activeSubview))activeSubview=meta.defaultSubview||'';title.textContent=t(meta.title);caption.textContent=t(meta.caption);document.getElementById('mobile-nav-label').textContent=t(`nav.${activeSection}`);renderSubnav(meta.subviews||[]);showLoading();try{await view.render(ctx,root);root.removeAttribute('aria-busy');status.textContent='';view.bind&&view.bind(ctx,root);if(focus)title.focus()}catch(error){showError(error)}}
  async function switchSection(name){activeSection=name;activeSubview='';document.querySelectorAll('.nav-item').forEach(button=>{const active=button.dataset.section===name;button.classList.toggle('active',active);if(active)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});document.getElementById('primary-nav').classList.remove('open');document.getElementById('mobile-nav-toggle').setAttribute('aria-expanded','false');history.replaceState(null,'','#'+name);await renderSection()}
  document.querySelectorAll('.nav-item').forEach(button=>button.onclick=()=>switchSection(button.dataset.section));
  document.getElementById('mobile-nav-toggle').onclick=()=>{const nav=document.getElementById('primary-nav'),open=nav.classList.toggle('open');document.getElementById('mobile-nav-toggle').setAttribute('aria-expanded',String(open))};
  locale=storageGet('plana_dashboard_locale')||'zh-CN';document.getElementById('locale-toggle').addEventListener('click',()=>{locale=locale==='zh-CN'?'en-US':'zh-CN';storageSet('plana_dashboard_locale',locale);applyI18n();renderSection(false)});
  const theme=storageGet('plana_dashboard_theme')||'light';document.body.dataset.theme=theme;document.getElementById('theme-toggle').setAttribute('aria-pressed',String(theme==='dark'));document.getElementById('theme-toggle').addEventListener('click',()=>{const next=document.body.dataset.theme==='dark'?'light':'dark';document.body.dataset.theme=next;storageSet('plana_dashboard_theme',next);document.getElementById('theme-toggle').setAttribute('aria-pressed',String(next==='dark'))});
  applyI18n();const requested=location.hash.slice(1);if(window.PlanaViews&&window.PlanaViews[requested])activeSection=requested;await switchSection(activeSection);
})();
