from __future__ import annotations

REVIEW_TAG = "needs-review"
SAFE_TAG = "safety:safe"
RESTRICTED_TAG = "safety:restricted"
CHAT_CONTRACT_VERSION = "plana.gallery.candidates.v1"
CHAT_FEEDBACK_VERSION = "plana.gallery.feedback.v1"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".gif", ".bmp"}

FACET_PREFIXES = {"emotion", "tone", "scene", "role", "intensity", "safety"}

DEFAULT_TAGS = (
    ("emotion:happy", "情绪", "开心", "愉快、满足或一般积极回应"),
    ("emotion:excited", "情绪", "兴奋", "期待实现、强烈开心或激动庆祝"),
    ("emotion:amused", "情绪", "觉得好笑", "被逗笑、看乐子或轻松搞怪"),
    ("emotion:affection", "情绪", "喜欢", "喜爱、亲近、宠溺或温柔回应"),
    ("emotion:grateful", "情绪", "感谢", "感谢、被帮助或感到暖心"),
    ("emotion:proud", "情绪", "得意", "自豪、得意或完成目标后的满足"),
    ("emotion:relieved", "情绪", "松口气", "风险解除、终于完成或压力下降"),
    ("emotion:hopeful", "情绪", "期待", "对接下来结果抱有希望、期待或积极预期"),
    ("emotion:playful", "情绪", "俏皮", "卖萌、坏笑、轻度捉弄或活泼互动"),
    ("emotion:calm", "情绪", "平静", "放松、安稳或低唤醒度的中性积极状态"),
    ("emotion:surprised", "情绪", "惊讶", "意外、震惊或突然发现"),
    ("emotion:confused", "情绪", "困惑", "不理解、迷茫或需要进一步确认"),
    ("emotion:curious", "情绪", "好奇", "想了解后续、观察新鲜事物或主动探究"),
    ("emotion:speechless", "情绪", "无语", "离谱、无奈或不知道如何回应"),
    ("emotion:helpless", "情绪", "无奈", "知道状况却难以改变、叹气或被迫接受"),
    ("emotion:shy", "情绪", "害羞", "被夸、亲密互动或轻微不好意思"),
    ("emotion:embarrassed", "情绪", "尴尬", "社交尴尬、出糗或想回避现场"),
    ("emotion:sad", "情绪", "难过", "悲伤、失落或受到打击"),
    ("emotion:wronged", "情绪", "委屈", "受到误解、被欺负或含泪表达不公平"),
    ("emotion:disappointed", "情绪", "失望", "期待落空、遗憾或结果不理想"),
    ("emotion:frustrated", "情绪", "挫败", "努力受阻、反复失败或无从下手"),
    ("emotion:guilty", "情绪", "内疚", "意识到过失、做错事或希望得到原谅"),
    ("emotion:angry", "情绪", "生气", "愤怒、强烈不满或明确反对"),
    ("emotion:annoyed", "情绪", "烦躁", "轻度生气、被打扰或不耐烦"),
    ("emotion:afraid", "情绪", "害怕", "恐惧、受惊或感到威胁"),
    ("emotion:nervous", "情绪", "紧张", "担心结果、焦虑或坐立不安"),
    ("emotion:panicked", "情绪", "慌张", "突发状况下明显失措、急迫或惊慌"),
    ("emotion:disgusted", "情绪", "嫌弃", "反感、恶心或强烈排斥"),
    ("emotion:tired", "情绪", "疲惫", "累、没精神或需要休息"),
    ("emotion:bored", "情绪", "无聊", "缺少兴趣、等待过久或想找点事情"),
    ("emotion:comfort", "情绪", "关怀", "用于安慰、陪伴和表达关心的回应倾向"),
    ("tone:teasing", "语气", "调侃", "轻松开玩笑，不用于攻击或冲突"),
    ("tone:agree", "语气", "赞同", "认可对方观点或表达支持"),
    ("tone:complain", "语气", "吐槽", "对事情表达轻度不满或无奈"),
    ("tone:encourage", "语气", "鼓励", "支持对方继续、尝试或恢复信心"),
    ("tone:question", "语气", "疑惑", "对信息提出疑问或请求澄清"),
    ("scene:greeting", "场景", "问候", "早安、晚安、欢迎或一般打招呼"),
    ("scene:celebrate", "场景", "庆祝", "完成、获胜、达成目标或收到好消息"),
    ("scene:refuse", "场景", "拒绝", "礼貌拒绝或表达不愿意"),
    ("scene:wait", "场景", "等待", "等待结果、处理中或暂时停留"),
    ("scene:apology", "场景", "道歉", "承认疏忽、表达歉意或请求原谅"),
    ("scene:end", "场景", "结束话题", "收尾、告别或暂时结束交流"),
    ("role:plana", "角色", "Plana", "明确描绘 Plana 的角色反应图"),
    ("role:generic", "角色", "通用", "不依赖特定角色身份的反应图"),
    ("intensity:1", "强度", "轻", "轻微情绪，不抢占聊天内容"),
    ("intensity:2", "强度", "中", "清晰情绪，适合一般聊天反应"),
    ("intensity:3", "强度", "强", "强烈情绪，仅在明确语境使用"),
    (SAFE_TAG, "安全", "普通聊天可用", "已人工确认，可用于普通聊天反应图"),
    (RESTRICTED_TAG, "安全", "限制使用", "仅在管理端可见，不进入普通聊天候选"),
)

DEFAULT_ALIASES = {
    "开心": "emotion:happy", "高兴": "emotion:happy",
    "快乐": "emotion:happy", "兴奋": "emotion:excited", "激动": "emotion:excited",
    "好笑": "emotion:amused", "被逗笑": "emotion:amused",
    "喜欢": "emotion:affection", "喜爱": "emotion:affection", "宠溺": "emotion:affection",
    "感谢": "emotion:grateful", "感激": "emotion:grateful", "暖心": "emotion:grateful",
    "得意": "emotion:proud", "自豪": "emotion:proud",
    "松口气": "emotion:relieved", "放心": "emotion:relieved",
    "期待": "emotion:hopeful", "希望": "emotion:hopeful", "盼望": "emotion:hopeful",
    "俏皮": "emotion:playful", "卖萌": "emotion:playful", "坏笑": "emotion:playful",
    "平静": "emotion:calm", "淡定": "emotion:calm", "安稳": "emotion:calm",
    "惊讶": "emotion:surprised", "震惊": "emotion:surprised",
    "困惑": "emotion:confused", "迷茫": "emotion:confused",
    "好奇": "emotion:curious", "想看看": "emotion:curious",
    "无语": "emotion:speechless", "无奈": "emotion:helpless", "叹气": "emotion:helpless",
    "害羞": "emotion:shy",
    "尴尬": "emotion:embarrassed", "难过": "emotion:sad", "伤心": "emotion:sad",
    "委屈": "emotion:wronged", "被欺负": "emotion:wronged",
    "失望": "emotion:disappointed", "遗憾": "emotion:disappointed",
    "挫败": "emotion:frustrated", "受挫": "emotion:frustrated",
    "内疚": "emotion:guilty", "愧疚": "emotion:guilty",
    "生气": "emotion:angry", "愤怒": "emotion:angry",
    "烦躁": "emotion:annoyed", "不耐烦": "emotion:annoyed",
    "害怕": "emotion:afraid", "恐惧": "emotion:afraid",
    "紧张": "emotion:nervous", "焦虑": "emotion:nervous",
    "慌张": "emotion:panicked", "惊慌": "emotion:panicked", "手忙脚乱": "emotion:panicked",
    "嫌弃": "emotion:disgusted", "反感": "emotion:disgusted",
    "疲惫": "emotion:tired", "累": "emotion:tired",
    "无聊": "emotion:bored", "安慰": "emotion:comfort", "关怀": "emotion:comfort",
    "调侃": "tone:teasing", "赞同": "tone:agree",
    "吐槽": "tone:complain", "鼓励": "tone:encourage",
    "疑惑": "tone:question", "问候": "scene:greeting",
    "庆祝": "scene:celebrate", "拒绝": "scene:refuse",
    "等待": "scene:wait", "道歉": "scene:apology",
    "结束": "scene:end", "普拉娜": "role:plana", "安全": SAFE_TAG,
}
